server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://39.108.66.223:3306/glzdept?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/mysql/*Mapper.xml