server:
  port: 8080
  compression:
    enabled: true
    mime: text/html,image/png,text/plain,text/css,application/javascript,application/json,application/x-font-ttf,application/x-font-otf,image/svg+xml,image/jpeg,image/gif,audio/mpeg,video/mp4
    min-response-size: 2048
spring:
  datasource:
    url: jdbc:mysql://39.108.66.223:3306/glzdeptdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/mysql/*Mapper.xml